name: Docker Build

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'

env:
  REPOSITORY: bird
  PACKAGE_REGISTRY: ghcr.io

jobs:
  build:
    name: Build Testing
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and cache
        uses: docker/build-push-action@v2
        with:
          target: builder
          platforms: |
            linux/386
            linux/amd64
            linux/arm/v5
            linux/arm/v7
            linux/arm64/v8
            linux/mips64le
            linux/ppc64le
            linux/s390x
          cache-to: type=gha, mode=max
          outputs: type=cacheonly
