name: Docker Publish

on:
  release:
    types:
      - published

env:
  USERNAME: akafeng
  REPOSITORY: bird
  PACKAGE_REGISTRY: ghcr.io

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Process Version
        id: version
        uses: ncipollo/semantic-version-action@v1

      - name: Docker Login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.PACKAGE_REGISTRY }} -u ${{ env.USERNAME }} --password-stdin

      - name: Docker Build
        env:
          STAGE_CACHE: ${{ env.PACKAGE_REGISTRY }}/${{ env.USERNAME }}/${{ env.REPOSITORY }}:stage
          MAJOR_TAG: ${{ env.PACKAGE_REGISTRY }}/${{ env.USERNAME }}/${{ env.REPOSITORY }}:${{ steps.version.outputs.major }}
          MINOR_TAG: ${{ env.PACKAGE_REGISTRY }}/${{ env.USERNAME }}/${{ env.REPOSITORY }}:${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}
          PATCH_TAG: ${{ env.PACKAGE_REGISTRY }}/${{ env.USERNAME }}/${{ env.REPOSITORY }}:${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }}
          LATEST_TAG: ${{ env.PACKAGE_REGISTRY }}/${{ env.USERNAME }}/${{ env.REPOSITORY }}:latest
        run: |
          docker pull ${{ env.STAGE_CACHE }} || true
          docker build \
            --cache-from=${{ env.STAGE_CACHE }} \
            --tag=${{ env.MAJOR_TAG }} \
            --tag=${{ env.MINOR_TAG }} \
            --tag=${{ env.PATCH_TAG }} \
            --tag=${{ env.LATEST_TAG }} \
            .
          docker image rm ${{ env.STAGE_CACHE }} || true

      - name: Docker Publish
        run: docker push --all-tags ${{ env.PACKAGE_REGISTRY }}/${{ env.USERNAME }}/${{ env.REPOSITORY }}
